repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: detect-private-key
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--line-length=100", "--python-version=38"]
- repo: https://github.com/psf/black
  rev: 23.9.0
  hooks:
    - id: black
      args: ["--line-length=100", "--target-version=py38"]
