plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - assets: [ "CHANGELOG.md" ]
  - "semantic-release-pypi"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md", "setup.cfg"]
branches:
  - main
